version: '3.7'

services:
  database:
    image: postgres:14
    container_name: e2e
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
